version: "3"
services:
  web:
    build: server
    ports:
      - "8080:8080"
    environment:
      - GSB_API_KEY
      - MYSQL_HOST=mysql-docker
      - MYSQL_PORT=3307
      - KEYCLOAK_HOST=keycloak
    depends_on:
      - mysql-docker
      - keycloak

  # Web Application MySQL database
  mysql-docker:
    image: library/mysql:5.7.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=urly
      - MYSQL_USER=urly
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3307
    ports:
      - '3307:3307'
    volumes:
      - mysqldocker:/var/lib/mysql

  # Keycloak Service
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql-keycloak
      - DB_DATABASE=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost:8081/auth
    ports:
      - '8081:8081'
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/config/user-realm-export.json"
      - "-Djboss.socket.binding.port-offset=1"
    volumes:
      - ./keycloak/config:/config/
    depends_on:
      - mysql-keycloak

  # Keycloak MySQL database
  mysql-keycloak:
    image: library/mysql:5.7.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - mysqlkeycloak:/var/lib/mysql

# Names our volume
volumes:
  mysqldocker:
  mysqlkeycloak: