version: "3"
services:
  web:
    build: server
    ports:
      - "8080:8080"
    environment:
      - GSB_API_KEY
      - MYSQL_HOST=mysql-docker
      - MYSQL_PORT=3307
    depends_on:
      - mysql-docker
      - rabbitmq
  systeminformation:
    build: systeminformation
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=mysql-docker
      - MYSQL_PORT=3307
    depends_on:
      - mysql-docker
      - rabbitmq
  mysql-docker:
    image: library/mysql:5.7.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=urly
      - MYSQL_USER=urly
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3307
    ports:
      - '3307:3307'
    volumes:
      - mysqldocker:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '15672:15672'
# Names our volume
volumes:
  mysqldocker: