version: "3"
services:
  web:
    build: server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/urly?useSSL=false
      - GSB_API_KEY
    depends_on:
      - mysql-docker
  mysql-docker:
    image: library/mysql:5.7.32
    container_name: mysql-docker
    command: --disable-partition-engine-check
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=urly
      - MYSQL_USER=urly
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: