version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GSB_API_KEY
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=urly
      - MYSQL_USER=urly
      - MYSQL_PASSWORD=password
    ports:
    - 3306:3306