version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GSB_API_KEY
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"